package view;

import java.awt.Color;
import java.util.Vector;
import javax.swing.JOptionPane;
import model.dao.PartidaDAO;
import view.adm.AlterarAdm;
import view.adm.AlterarPartida;
import view.adm.AlterarTime;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brhue
 */
public class Principal extends javax.swing.JFrame {
    private AlterarTime alterarTime = null;
    private AlterarPartida alterarPartida = null;
    private AlterarAdm alterarAdm = null;
    
    
    public void setInvisivel(boolean invisible){
        // Defini se os componentes de Principal serão visiveis ou não
        this.panelPrincipal.setVisible(!invisible);
    }
    
    public void setVisivelAdm(){
        //Se falso, aparece
        if(!panelPrincipalAdm.isVisible()){
            panelPrincipalAdm.setVisible(true);
        }
    }
    
 
    public void comboPartida(){
        Vector vectorPartida = PartidaDAO.partidasCombo();
        for (int i=0; i<vectorPartida.size();i++){
            comboPartidaA.addItem(vectorPartida.elementAt(i).toString());
        }
    }
    public void meuInitUser(int tipo_user){
        // PRINCIPAL VISTO PELO USUÁRIO COMUM
        if(tipo_user == 0){
            this.menuPartida.setVisible(false);
            this.menuTime.setVisible(false);
            this.criarADM.setVisible(false);
        }else{
            setInvisivel(true);
            this.getContentPane().setBackground(Color.WHITE);
        }
        
        
    }
    
    public void meuInitUser(){
        setInvisivel(true);
        comboPartida();
    }
    
    public Principal(int tipo_user) {
        initComponents();
        panelPrincipal.setBackground(Color.WHITE);
        meuInitUser(tipo_user);
        comboPartida();
        
    }
    
    public Principal(){
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        cbTime1 = new javax.swing.JCheckBox();
        cbTime2 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        btnApostar = new javax.swing.JButton();
        comboPartidaA = new javax.swing.JComboBox<>();
        panelPrincipalAdm = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        meuOpcoes = new javax.swing.JMenu();
        criarADM = new javax.swing.JMenuItem();
        iMenuSair = new javax.swing.JMenuItem();
        menuPartida = new javax.swing.JMenu();
        iMenuAlterarP = new javax.swing.JMenuItem();
        menuTime = new javax.swing.JMenu();
        iMenuAlterarT = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cbTime1.setText("jCheckBox1");

        cbTime2.setText("jCheckBox2");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("VS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(cbTime1)
                .addGap(111, 111, 111)
                .addComponent(jLabel6)
                .addGap(115, 115, 115)
                .addComponent(cbTime2)
                .addGap(91, 91, 91))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTime1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbTime2)
                            .addComponent(jLabel6))))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btnApostar.setText("Apostar");

        comboPartidaA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a partida" }));
        comboPartidaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPartidaAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(comboPartidaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(btnApostar)
                        .addGap(258, 258, 258))))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(comboPartidaA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnApostar)
                .addContainerGap(334, Short.MAX_VALUE))
        );

        panelPrincipalAdm.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipalAdm.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoPequeno.png"))); // NOI18N
        panelPrincipalAdm.add(jLabel7);
        jLabel7.setBounds(260, 40, 70, 70);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Pick Fantasy");
        panelPrincipalAdm.add(jLabel1);
        jLabel1.setBounds(230, 100, 180, 50);

        jLabel8.setText("ADMINISTRADOR");
        panelPrincipalAdm.add(jLabel8);
        jLabel8.setBounds(255, 150, 120, 14);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 153));
        panelPrincipalAdm.add(jSeparator1);
        jSeparator1.setBounds(10, 190, 576, 16);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gearwheelPequeno.png"))); // NOI18N
        panelPrincipalAdm.add(jLabel9);
        jLabel9.setBounds(40, 230, 50, 50);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel10.setText("Adicione ou remova partidas");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 10, 200, 14);

        jLabel12.setText("Altere os placares das partidas");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(80, 30, 220, 14);

        jLabel11.setText("Adicione ou remova times");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 50, 210, 14);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 204, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)))
        );

        panelPrincipalAdm.add(jPanel3);
        jPanel3.setBounds(30, 210, 500, 100);

        meuOpcoes.setText("Opções");
        meuOpcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                meuOpcoesMouseClicked(evt);
            }
        });

        criarADM.setText("Criar ADM");
        criarADM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criarADMMouseClicked(evt);
            }
        });
        criarADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarADMActionPerformed(evt);
            }
        });
        meuOpcoes.add(criarADM);

        iMenuSair.setText("Sair");
        iMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMenuSairActionPerformed(evt);
            }
        });
        meuOpcoes.add(iMenuSair);

        jMenuBar1.add(meuOpcoes);

        menuPartida.setText("Partida");

        iMenuAlterarP.setText("Alterar Partida");
        iMenuAlterarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iMenuAlterarPMouseClicked(evt);
            }
        });
        iMenuAlterarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMenuAlterarPActionPerformed(evt);
            }
        });
        menuPartida.add(iMenuAlterarP);

        jMenuBar1.add(menuPartida);

        menuTime.setText("Time");

        iMenuAlterarT.setText("Alterar Time");
        iMenuAlterarT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iMenuAlterarTMouseClicked(evt);
            }
        });
        iMenuAlterarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iMenuAlterarTActionPerformed(evt);
            }
        });
        menuTime.add(iMenuAlterarT);

        jMenuBar1.add(menuTime);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPrincipalAdm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelPrincipalAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboPartidaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPartidaAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPartidaAActionPerformed

    private void meuOpcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meuOpcoesMouseClicked

    }//GEN-LAST:event_meuOpcoesMouseClicked

    private void iMenuAlterarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMenuAlterarPActionPerformed
        //Abrir Janela AlterarPartida
        panelPrincipalAdm.setVisible(false);
       if(alterarTime != null){
           alterarTime.setVisible(false);
       }
      
        if(alterarPartida == null){
            alterarPartida = new AlterarPartida(this);
            this.add(alterarPartida);
        }alterarPartida.setVisible(true);
        
    }//GEN-LAST:event_iMenuAlterarPActionPerformed

    private void iMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMenuSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_iMenuSairActionPerformed

    private void iMenuAlterarTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMenuAlterarTMouseClicked

    }//GEN-LAST:event_iMenuAlterarTMouseClicked

    private void iMenuAlterarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iMenuAlterarTActionPerformed
        //setInvisivel(true);
        panelPrincipalAdm.setVisible(false);
         
        if(alterarPartida != null){
            alterarPartida.setVisible(false);
        }
        
        if(alterarTime == null){
            alterarTime = new AlterarTime(this);
            this.add(alterarTime);
        }alterarTime.setVisible(true);
        
    }//GEN-LAST:event_iMenuAlterarTActionPerformed

    private void iMenuAlterarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iMenuAlterarPMouseClicked

    }//GEN-LAST:event_iMenuAlterarPMouseClicked

    private void criarADMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criarADMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_criarADMMouseClicked

    private void criarADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarADMActionPerformed
        // TODO add your handling code here:
        //setInvisivel(true);
       /* panelPrincipalAdm.setVisible(false);
        
        if(alterarTime != null){
           alterarTime.setVisible(false);
       }else if(alterarPartida != null){
           alterarPartida.setVisible(false);
       }
        if(alterarAdm ==null){
            alterarAdm = new AlterarAdm(this);
            this.add(alterarAdm);
        }alterarAdm.setVisible(true);*/
       
       new AlterarAdm(this).setVisible(true);
       
    }//GEN-LAST:event_criarADMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApostar;
    private javax.swing.JCheckBox cbTime1;
    private javax.swing.JCheckBox cbTime2;
    private javax.swing.JComboBox<String> comboPartidaA;
    private javax.swing.JMenuItem criarADM;
    private javax.swing.JMenuItem iMenuAlterarP;
    private javax.swing.JMenuItem iMenuAlterarT;
    private javax.swing.JMenuItem iMenuSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu menuPartida;
    private javax.swing.JMenu menuTime;
    private javax.swing.JMenu meuOpcoes;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelPrincipalAdm;
    // End of variables declaration//GEN-END:variables
}
